### PR TITLE
Added !charles request

### PR DESCRIPTION
**Pull request by jumblesale**
a good dog

### CODE REVIEW

**Comment by michael-donat** [comment]
http://54.187.82.33:1627/random ?

Not responding currently.

**Comment by jumblesale** [comment]
Works OK here. Will investigate...
On 11 May 2014 14:21, "Michael Donat" notifications@github.com wrote:

> http://54.187.82.33:1627/random ?
> 
> Not responding currently.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/monitechnologies/moni.to.r/pull/3#issuecomment-42770412
> .

## 

---

The contents of this email are confidential to Moni Technologies Ltd and 
intended to be received by the addressee(s) only. If you have received this 
email in error, please promptly notify us by reply and delete it, along 
with all copies in your possession. The unauthorised use, disclosure or 
copying of this email, or its contents, is prohibited. Any opinion 
expressed in this email is personal to the sender and in no way represents 
the views of Moni Technologies Ltd. This email cannot be relied upon to 
create a contract or any obligation on the part of Moni Technologies Ltd. 
All e-mail passing through the Company's e-mail systems may be subject to 
monitoring. Moni Technologies Ltd accepts no liability for errors or 
viruses.  

Moni Technologies Ltd is a company incorporated in England and Wales (Reg. 
No. 07990859) with its registered office at Finsgate, 5-7 Cranwood 
St, London, Greater London EC1V 9EE. 

Moni Technologies Ltd is a registered money service business. Her Majesty's 
Revenue and Customs certificate number 12689060.
Moni Technologies Limited is registered with the Financial Services 
Authority under the Payment Service Regulations 2009 (FRN 582759) for the 
provision of payment services.

**Comment by jumblesale** [comment]
http://54.187.82.33:16217/random

**Comment by michael-donat** [comment]
It takes ages to render each picture ;)

On 11 May 2014, at 19:09, jumblesale notifications@github.com wrote:

> http://54.187.82.33:16217/random
> 
> —
> Reply to this email directly or view it on GitHub.

## 

---

The contents of this email are confidential to Moni Technologies Ltd and 
intended to be received by the addressee(s) only. If you have received this 
email in error, please promptly notify us by reply and delete it, along 
with all copies in your possession. The unauthorised use, disclosure or 
copying of this email, or its contents, is prohibited. Any opinion 
expressed in this email is personal to the sender and in no way represents 
the views of Moni Technologies Ltd. This email cannot be relied upon to 
create a contract or any obligation on the part of Moni Technologies Ltd. 
All e-mail passing through the Company's e-mail systems may be subject to 
monitoring. Moni Technologies Ltd accepts no liability for errors or 
viruses.  

Moni Technologies Ltd is a company incorporated in England and Wales (Reg. 
No. 07990859) with its registered office at Finsgate, 5-7 Cranwood 
St, London, Greater London EC1V 9EE. 

Moni Technologies Ltd is a registered money service business. Her Majesty's 
Revenue and Customs certificate number 12689060.
Moni Technologies Limited is registered with the Financial Services 
Authority under the Payment Service Regulations 2009 (FRN 582759) for the 
provision of payment services.

**Comment by michael-donat** [comment]
Can you also add http:// in the response?

On 11 May 2014, at 19:12, Michael Donat michael@monitechnologies.com wrote:

> It takes ages to render each picture ;)
> 
> On 11 May 2014, at 19:09, jumblesale notifications@github.com wrote:
> 
> > http://54.187.82.33:16217/random
> > 
> > —
> > Reply to this email directly or view it on GitHub.

## 

---

The contents of this email are confidential to Moni Technologies Ltd and 
intended to be received by the addressee(s) only. If you have received this 
email in error, please promptly notify us by reply and delete it, along 
with all copies in your possession. The unauthorised use, disclosure or 
copying of this email, or its contents, is prohibited. Any opinion 
expressed in this email is personal to the sender and in no way represents 
the views of Moni Technologies Ltd. This email cannot be relied upon to 
create a contract or any obligation on the part of Moni Technologies Ltd. 
All e-mail passing through the Company's e-mail systems may be subject to 
monitoring. Moni Technologies Ltd accepts no liability for errors or 
viruses.  

Moni Technologies Ltd is a company incorporated in England and Wales (Reg. 
No. 07990859) with its registered office at Finsgate, 5-7 Cranwood 
St, London, Greater London EC1V 9EE. 

Moni Technologies Ltd is a registered money service business. Her Majesty's 
Revenue and Customs certificate number 12689060.
Moni Technologies Limited is registered with the Financial Services 
Authority under the Payment Service Regulations 2009 (FRN 582759) for the 
provision of payment services.

**Comment by jumblesale** [comment]
Done! It's uncompressed photos on dropbox being served over a free AWS instance so I expect it's a little slow :)

**Comment by michael-donat** [comment]
I meant that the photos are HUMONGOUS! 

On 11 May 2014, at 20:29, jumblesale notifications@github.com wrote:

> Done! It's uncompressed photos on dropbox being served over a free AWS instance so I expect it's a little slow :)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

---

The contents of this email are confidential to Moni Technologies Ltd and 
intended to be received by the addressee(s) only. If you have received this 
email in error, please promptly notify us by reply and delete it, along 
with all copies in your possession. The unauthorised use, disclosure or 
copying of this email, or its contents, is prohibited. Any opinion 
expressed in this email is personal to the sender and in no way represents 
the views of Moni Technologies Ltd. This email cannot be relied upon to 
create a contract or any obligation on the part of Moni Technologies Ltd. 
All e-mail passing through the Company's e-mail systems may be subject to 
monitoring. Moni Technologies Ltd accepts no liability for errors or 
viruses.  

Moni Technologies Ltd is a company incorporated in England and Wales (Reg. 
No. 07990859) with its registered office at Finsgate, 5-7 Cranwood 
St, London, Greater London EC1V 9EE. 

Moni Technologies Ltd is a registered money service business. Her Majesty's 
Revenue and Customs certificate number 12689060.
Moni Technologies Limited is registered with the Financial Services 
Authority under the Payment Service Regulations 2009 (FRN 582759) for the 
provision of payment services.

**Pull request merged**
